//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppForSHA256.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change
    {
        public int ID_Change { get; set; }
        public Nullable<int> ID_Patern { get; set; }
        public Nullable<int> ID_Group { get; set; }
        public Nullable<int> NumWorkshop { get; set; }
        public Nullable<int> QuantityShoes { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Pattern Pattern { get; set; }
    }
}
