//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppForSHA256.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialApplication
    {
        public int ID_MaterialApplication { get; set; }
        public int ID_Material { get; set; }
        public int ID_SupplierCompani { get; set; }
        public int Quantity { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual SupplierCompani SupplierCompani { get; set; }
    }
}
