//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppForSHA256.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionCosts
    {
        public int ID_ProductionCosts { get; set; }
        public int ID_Model { get; set; }
        public long SelfCostModel { get; set; }
        public long ProductionCost { get; set; }
        public Nullable<int> SellCost { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
