//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamWork1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int ID_Feedback { get; set; }
        public string Author { get; set; }
        public string Text { get; set; }
        public string ContactDetails { get; set; }
        public int ID_TypeFB { get; set; }
        public int ID_Order { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual TypeFB TypeFB { get; set; }
    }
}
