//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamWork1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int ID_OrderList { get; set; }
        public int ID_Order { get; set; }
        public int ID_Model { get; set; }
        public int Quantity { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual Order Order { get; set; }
    }
}
