//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamWork1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeTable
    {
        public int ID_SizeTable { get; set; }
        public int ID_Size { get; set; }
        public Nullable<int> ID_Model { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual Size Size { get; set; }
    }
}
