//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamWork1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WasteRequest
    {
        public int ID_WasteRequest { get; set; }
        public int ID_RecyclingCompany { get; set; }
        public int ID_Wastes { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual RecyclingCompany RecyclingCompany { get; set; }
        public virtual Wastes Wastes { get; set; }
    }
}
